In [1]:
import pandas as pd
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score,precision_score,recall_score,f1_score

In [2]:
df1 = pd.read_csv('datasets1.csv')
print("Dataset 'datasets1.csv' loaded successfully!")
df2 = pd.read_csv('datasets2.csv')
print("Dataset 'datasets2.csv' loaded successfully!")

df = pd.concat([df1, df2])
print("Datasets concatenated successfully!")

X = df.iloc[:, :-1]  # เลือกทุกคอลัมน์ยกเว้นคอลัมน์สุดท้าย
y = df.iloc[:, -1]   # เลือกคอลัมน์สุดท้ายเป็น target
print("----------Everything Successfully!----------")

Dataset 'datasets1.csv' loaded successfully!
Dataset 'datasets2.csv' loaded successfully!
Datasets concatenated successfully!
----------Everything Successfully!----------


In [3]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)

In [4]:
KNN = KNeighborsClassifier()

In [5]:
param_grid={
    'n_neighbors':np.arange(1,10),
    'weights':['uniform','distance'],
    'algorithm':['ball_tree', 'kd_tree', 'brute'],
    'metric':['euclidean','manhattan','minkowski','conies'],
    'p':[1,2,3]
}
Kgrid=GridSearchCV(KNN,param_grid,refit=True,verbose=3,cv=5)
Kgrid.fit(X_train,y_train)

Fitting 5 folds for each of 648 candidates, totalling 3240 fits
[CV 1/5] END algorithm=ball_tree, metric=euclidean, n_neighbors=1, p=1, weights=uniform;, score=0.919 total time=   4.2s
[CV 2/5] END algorithm=ball_tree, metric=euclidean, n_neighbors=1, p=1, weights=uniform;, score=0.918 total time=   4.3s
[CV 3/5] END algorithm=ball_tree, metric=euclidean, n_neighbors=1, p=1, weights=uniform;, score=0.921 total time=   4.2s
[CV 4/5] END algorithm=ball_tree, metric=euclidean, n_neighbors=1, p=1, weights=uniform;, score=0.911 total time=   4.3s
[CV 5/5] END algorithm=ball_tree, metric=euclidean, n_neighbors=1, p=1, weights=uniform;, score=0.919 total time=   4.4s
[CV 1/5] END algorithm=ball_tree, metric=euclidean, n_neighbors=1, p=1, weights=distance;, score=0.919 total time=   4.4s
[CV 2/5] END algorithm=ball_tree, metric=euclidean, n_neighbors=1, p=1, weights=distance;, score=0.918 total time=   4.6s
[CV 3/5] END algorithm=ball_tree, metric=euclidean, n_neighbors=1, p=1, weights=distanc

C:\Users\COLORFUL\anaconda3\envs\Machine_Learning\Lib\site-packages\sklearn\model_selection\_validation.py:516: FitFailedWarning: 
810 fits failed out of a total of 3240.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
810 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\COLORFUL\anaconda3\envs\Machine_Learning\Lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\COLORFUL\anaconda3\envs\Machine_Learning\Lib\site-packages\sklearn\base.py", line 1358, in wrapper
    estimator._validate_params()
  File "C:\Users\COLORFUL\anaconda3\envs\Machine_Learning\Lib\site-packages\sklearn\base.py", line 471, in 

,estimator,KNeighborsClassifier()
,param_grid,"{'algorithm': ['ball_tree', 'kd_tree', ...], 'metric': ['euclidean', 'manhattan', ...], 'n_neighbors': array([1, 2, ..., 6, 7, 8, 9]), 'p': [1, 2, ...], ...}"
,scoring,None
,n_jobs,None
,refit,True
,cv,5
,verbose,3
,pre_dispatch,'2*n_jobs'
,error_score,nan
,return_train_score,False
,n_neighbors,np.int64(6)


In [6]:
print('Mean Accuracy: %.2f %%'%(Kgrid.best_score_*100))
print('Best Parameters',Kgrid.best_params_)

Mean Accuracy: 93.79 %
Best Parameters {'algorithm': 'ball_tree', 'metric': 'manhattan', 'n_neighbors': np.int64(6), 'p': 1, 'weights': 'distance'}


In [7]:
best_KNN = Kgrid.best_estimator_

In [8]:
y_pred = best_KNN.predict(X_test)

In [9]:
print(classification_report(y_test,y_pred))
print('confusion matrix:=\n',confusion_matrix(y_test,y_pred))
print('\nAccuracy:=',accuracy_score(y_test,y_pred)*100)
print('Precision:=',precision_score(y_test,y_pred,average='macro')*100)
print('Recall:=',recall_score(y_test,y_pred,average='macro')*100)
print('F1:=',f1_score(y_test,y_pred,average='macro')*100)

              precision    recall  f1-score   support

           1       0.95      0.98      0.97     15969
           2       0.79      0.62      0.69      1219
           3       0.92      0.87      0.89      3795

    accuracy                           0.94     20983
   macro avg       0.89      0.82      0.85     20983
weighted avg       0.94      0.94      0.94     20983

confusion matrix:=
 [[15639   148   182]
 [  351   754   114]
 [  432    50  3313]]

Accuracy:= 93.91412095505885
Precision:= 88.74398953022725
Recall:= 82.36218418456347
F1:= 85.17236819080912
